# Generated by Django 5.2 on 2025-06-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Име')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Коментар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Име на събитието')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='Начална дата')),
                ('end_date', models.DateField(verbose_name='Крайна дата')),
                ('start_time', models.TimeField(verbose_name='Дата на отваряне')),
                ('end_time', models.TimeField(verbose_name='Дата на затваряне')),
                ('location', models.CharField(max_length=255, verbose_name='Място на провеждане')),
            ],
        ),
    ]
