# Generated by Django 5.2 on 2025-05-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtaghub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Име на събитието')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('datetime', models.DateTimeField(verbose_name='Дата и час')),
                ('location', models.CharField(max_length=255, verbose_name='Място на провеждане')),
            ],
        ),
    ]
